# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: logspout-pipeline
  path.config: "/usr/share/logstash/pipeline/logspout.conf"

- pipeline.id: mysql-catalog-pipeline
  path.config: "/usr/share/logstash/pipeline/catalog.conf"

# - pipeline.id: incremental-pipeline
#   path.config: "/usr/share/logstash/pipeline/incremental.conf"