ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

USER logstash:root

WORKDIR /usr/share/logstash/

RUN curl -L --output "mysql-connector-java-8.0.22.tar.gz" "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.22.tar.gz" \
    && tar -xf "mysql-connector-java-8.0.22.tar.gz" "mysql-connector-java-8.0.22/mysql-connector-java-8.0.22.jar" \
    && mv "mysql-connector-java-8.0.22/mysql-connector-java-8.0.22.jar" "mysql-connector-java-8.0.22.jar" \
    && rm -r "mysql-connector-java-8.0.22" "mysql-connector-java-8.0.22.tar.gz"

RUN mkdir -p jdbc-last-run/neomed/
RUN touch jdbc-last-run/neomed/categories
RUN touch jdbc-last-run/neomed/products
RUN touch jdbc-last-run/neomed/distributors
RUN touch jdbc-last-run/neomed/providers
RUN touch jdbc-last-run/neomed/pharmacies